### ISSUE TITLE
Unable to use shopify.Session.temp method

### ISSUE THREAD

**Issue by abhi204** [Shopify/shopify_python_api#374] opened 2020-04-10 17:43 UTC
First of all, I would like to point out that in the Docs, the function is called with only 2 arguments: `shopify.Session.temp(domain, token)`
Whereas the one I use needs api-version to be passed as well: 
`shopify.Session.temp(domain, api_version,token)`

When I try to temporarily create a session Using shopify.Session.temp using with statement, I get the following error:
`Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/work/.local/share/virtualenvs/layer5_shopify_app-Ng61jmnB/lib/python3.8/site-packages/shopify/session.py", line 36, in temp
    original_version = shopify.ShopifyResource.get_version() or version
  File "/home/work/.local/share/virtualenvs/layer5_shopify_app-Ng61jmnB/lib/python3.8/site-packages/shopify/base.py", line 151, in get_version
    return ShopifyResource._site.split('/')[-1]
AttributeError: 'NoneType' object has no attribute 'split'`

Code to reproduce the error:

`import shopify`
`domain={SHOP-DOMAIN}`
`version='2020-01'`
`access_token={ACCESS-TOKEN}`
`with shopify.Session.temp(domain, version, access_token):`
`       # Do something`

**Comment by tanema** [comment] 2020-04-13 13:47
duplicate of #373

**Closed by tanema** 2020-04-13 13:47 UTC
