### ISSUE TITLE
Write requests to inventory_quantity and inventory_quantity_adjustment are no longer supported. Please use the Inventory Levels API

### ISSUE THREAD

**Issue by bg1hxp** [Shopify/shopify_python_api#368] opened 2020-03-23 20:08 UTC
change the product.variants, get the error.

**Comment by bg1hxp** [comment] 2020-03-23 20:08
shop = shopify.Shop.current()
product = shopify.Product.find(574703697985)
print(product.id)
print(product.variants[0].price)

product.variants[0].price = '81.00'
print(product.variants[0].price)

product.save()

**Comment by tanema** [comment] 2020-03-23 20:38
duplicate of #347 It has a workaround in the thread. I am sorry about the delay, we are rushing a few things out and hope to have someone fix this soon.

**Closed by tanema** 2020-03-23 20:38 UTC
