### ISSUE TITLE
RecurringApplicationCharge properties not updated on activate()

### ISSUE THREAD

**Issue by adamlwgriffiths** [Shopify/shopify_python_api#128] opened 2015-12-10 00:21 UTC
activate() calls the _load_from_response method, but the values are not updated.
billing_on, trial_ends_on, activated_on. These are all None.

I have to re-request the object post-activate to get these.

The shopify docs state that the activate call returns these values, so either the docs are wrong, or there's an issue in the python lib.

As an aside, for the love of god, create some decent documentation.

**Comment by kevinhughes27** [comment] 2015-12-21 21:30
@jamiemtdwyer can you look into this one?

**Comment by ch33sybr3ad** [comment] 2016-02-29 15:59
This issue should be fixed now. We used to return an empty body after activating a `recurring_application_charge`, but now we return the whole object

**Comment by kevinhughes27** [comment] 2016-02-29 16:11
@ch33sybr3ad can you confirm and close please

**Comment by jamiemtdwyer** [comment] 2018-10-01 15:37
Confirmed that this is working as intended now, the issue was with the response returned by Shopify which has been fixed.

```
>>> charge.activate()
>>> charge
recurring_application_charge(3073376278)
>>> charge.attributes
{'trial_ends_on': '2018-10-01', 'api_client_id': 1794825, 'activated_on': '2018-10-01', 'status': 'active', 'billing_on': '2018-10-01', 'created_at': '2018-10-01T11:35:43-04:00', 'decorated_return_url': 'https://www.google.com/?charge_id=3073376278', 'price': '19.99', 'trial_days': 0, 'cancelled_on': None, 'id': 3073376278, 'test': True, 'return_url': 'https://www.google.com/', 'updated_at': '2018-10-01T11:36:30-04:00', 'confirmation_url': 'https://jamie-ds-emporium.myshopify.com/admin/charges/3073376278/confirm_recurring_application_charge?signature=BAhsKwcWADC3--ddba402c8a491e11f67aadfc2e30ccb20a5f3423', 'name': 'Test charge'}
```

**Closed** 2018-10-01 15:37 UTC
